// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiMo6ryC49MgLfe6DqLKPs8cNAXmxMqW8',
    appId: '1:565082239551:web:045d4c9d33530825433e8a',
    messagingSenderId: '565082239551',
    projectId: 'fruits-2ad73',
    authDomain: 'fruits-2ad73.firebaseapp.com',
    storageBucket: 'fruits-2ad73.firebasestorage.app',
    measurementId: 'G-ZHGYG0TSCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWOKNQ4QZGI6h58I9fo_syRUB7larAXdM',
    appId: '1:565082239551:android:c35792db8b929483433e8a',
    messagingSenderId: '565082239551',
    projectId: 'fruits-2ad73',
    storageBucket: 'fruits-2ad73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8obZHARvobahjNj18TLJLj9yHt3Fyr7Y',
    appId: '1:565082239551:ios:805bce5a2c0f307b433e8a',
    messagingSenderId: '565082239551',
    projectId: 'fruits-2ad73',
    storageBucket: 'fruits-2ad73.firebasestorage.app',
    androidClientId: '565082239551-3bqeg8ke9qndis93en2iig6anommomts.apps.googleusercontent.com',
    iosClientId: '565082239551-808f5d4mqgtm0496obddsml88si010fa.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8obZHARvobahjNj18TLJLj9yHt3Fyr7Y',
    appId: '1:565082239551:ios:805bce5a2c0f307b433e8a',
    messagingSenderId: '565082239551',
    projectId: 'fruits-2ad73',
    storageBucket: 'fruits-2ad73.firebasestorage.app',
    androidClientId: '565082239551-3bqeg8ke9qndis93en2iig6anommomts.apps.googleusercontent.com',
    iosClientId: '565082239551-808f5d4mqgtm0496obddsml88si010fa.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiMo6ryC49MgLfe6DqLKPs8cNAXmxMqW8',
    appId: '1:565082239551:web:45a086bf9b9f6050433e8a',
    messagingSenderId: '565082239551',
    projectId: 'fruits-2ad73',
    authDomain: 'fruits-2ad73.firebaseapp.com',
    storageBucket: 'fruits-2ad73.firebasestorage.app',
    measurementId: 'G-Q6QWH41QKL',
  );
}
